import type { ClothingItem, Outfit } from "./types";

const u = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=80`;

export const SAMPLE_ITEMS: ClothingItem[] = [
  {
    id: "item-silk-blouse",
    name: "Ivory Silk Blouse",
    category: "Blouses",
    color: "Ivory",
    season: "All Season",
    brand: "Sézane",
    size: "S",
    notes: "Soft drape, tucks neatly into high-waist trousers.",
    image: u("photo-1594633312681-425c7b97ccd1"),
    favorite: true,
    createdAt: "2026-08-12T10:00:00.000Z",
  },
  {
    id: "item-cream-sweater",
    name: "Cashmere Crew Sweater",
    category: "Sweaters",
    color: "Cream",
    season: "Autumn",
    brand: "Everlane",
    size: "S",
    notes: "Lightweight cashmere. Perfect under a trench.",
    image: u("photo-1434389677669-e08b4cac3105"),
    favorite: true,
    createdAt: "2026-08-18T14:20:00.000Z",
  },
  {
    id: "item-navy-tee",
    name: "Navy Cotton Tee",
    category: "T-Shirts",
    color: "Navy",
    season: "Summer",
    brand: "Arket",
    size: "S",
    notes: "Fine rib, slightly cropped.",
    image: u("photo-1503342217505-b0a15ec3261c"),
    favorite: false,
    createdAt: "2026-07-02T09:10:00.000Z",
  },
  {
    id: "item-white-shirt",
    name: "Classic White Shirt",
    category: "Shirts",
    color: "White",
    season: "All Season",
    brand: "COS",
    size: "36",
    notes: "Crisp poplin with a relaxed shoulder.",
    image: u("photo-1596755094514-f87e34085b2c"),
    favorite: false,
    createdAt: "2026-06-21T11:00:00.000Z",
  },
  {
    id: "item-sage-cami",
    name: "Sage Linen Cami",
    category: "Tops",
    color: "Sage",
    season: "Summer",
    brand: "& Other Stories",
    size: "S",
    notes: "Square neck. Pairs with ivory trousers.",
    image: u("photo-1564255010-5e554c83ad60"),
    favorite: true,
    createdAt: "2026-07-19T16:40:00.000Z",
  },
  {
    id: "item-oat-hoodie",
    name: "Oat Oversized Hoodie",
    category: "Hoodies",
    color: "Beige",
    season: "Autumn",
    brand: "Aritzia",
    size: "XS",
    notes: "Weekend layer with bike shorts or jeans.",
    image: u("photo-1556821840-3a63f95609a7"),
    favorite: false,
    createdAt: "2026-08-01T08:30:00.000Z",
  },
  {
    id: "item-linen-dress",
    name: "Sand Linen Midi Dress",
    category: "Dresses",
    color: "Tan",
    season: "Summer",
    brand: "Reformation",
    size: "2",
    notes: "Tie waist. Travels well.",
    image: u("photo-1595777457583-95e059d581b8"),
    favorite: true,
    createdAt: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "item-black-dress",
    name: "Black Slip Dress",
    category: "Dresses",
    color: "Black",
    season: "All Season",
    brand: "Ganni",
    size: "34",
    notes: "Bias cut. Add a blazer for dinner.",
    image: u("photo-1566174053879-315285779f1c"),
    favorite: true,
    createdAt: "2026-05-14T19:00:00.000Z",
  },
  {
    id: "item-pleated-skirt",
    name: "Camel Pleated Skirt",
    category: "Skirts",
    color: "Camel",
    season: "Autumn",
    brand: "Massimo Dutti",
    size: "36",
    notes: "Midi length, sits at the waist.",
    image: u("photo-1583496661160-fb5886a0aaaa"),
    favorite: false,
    createdAt: "2026-08-05T13:15:00.000Z",
  },
  {
    id: "item-ivory-trousers",
    name: "Ivory Wide Trousers",
    category: "Pants",
    color: "Ivory",
    season: "Spring",
    brand: "Toteme",
    size: "34",
    notes: "Fluid drape. Hem brushes the floor in flats.",
    image: u("photo-1594633313593-bab3825d0caf"),
    favorite: true,
    createdAt: "2026-08-28T10:45:00.000Z",
  },
  {
    id: "item-blue-jeans",
    name: "Vintage Wash Jeans",
    category: "Jeans",
    color: "Blue",
    season: "All Season",
    brand: "Agolde",
    size: "25",
    notes: "Straight leg, slight crop.",
    image: u("photo-1541099649105-f69ad21f3246"),
    favorite: false,
    createdAt: "2026-04-09T15:00:00.000Z",
  },
  {
    id: "item-linen-shorts",
    name: "Cream Linen Shorts",
    category: "Shorts",
    color: "Cream",
    season: "Summer",
    brand: "Faithfull",
    size: "S",
    notes: "High waist, covered buttons.",
    image: u("photo-1591195853828-11db59a44f6b"),
    favorite: false,
    createdAt: "2026-06-30T09:50:00.000Z",
  },
  {
    id: "item-black-blazer",
    name: "Tailored Black Blazer",
    category: "Jackets",
    color: "Black",
    season: "All Season",
    brand: "The Row",
    size: "0",
    notes: "Strong shoulder, single button.",
    image: u("photo-1591369822096-ffd140ec948f"),
    favorite: true,
    createdAt: "2026-03-11T11:20:00.000Z",
  },
  {
    id: "item-trench",
    name: "Honey Trench Coat",
    category: "Coats",
    color: "Camel",
    season: "Spring",
    brand: "Burberry",
    size: "6",
    notes: "Classic belted trench. City uniform.",
    image: u("photo-1520012212540-5c69d0e12943"),
    favorite: true,
    createdAt: "2026-03-22T17:00:00.000Z",
  },
  {
    id: "item-slingbacks",
    name: "Nude Slingback Heels",
    category: "Shoes",
    color: "Beige",
    season: "All Season",
    brand: "Mango",
    size: "37",
    notes: "Kitten heel. Walkable for dinners.",
    image: u("photo-1543163521-1bf539c55dd2"),
    favorite: true,
    createdAt: "2026-08-09T18:10:00.000Z",
  },
  {
    id: "item-ballet-flats",
    name: "Black Ballet Flats",
    category: "Shoes",
    color: "Black",
    season: "All Season",
    brand: "Mansur Gavriel",
    size: "37",
    notes: "Soft leather, everyday elegance.",
    image: u("photo-1518049362265-d281bdeae5d1"),
    favorite: false,
    createdAt: "2026-05-01T08:00:00.000Z",
  },
  {
    id: "item-cream-bag",
    name: "Structured Cream Bag",
    category: "Bags",
    color: "Cream",
    season: "All Season",
    brand: "Polène",
    size: "One size",
    notes: "Holds a compact and sunglasses.",
    image: u("photo-1584917865442-de89df76afd3"),
    favorite: true,
    createdAt: "2026-07-28T12:30:00.000Z",
  },
  {
    id: "item-gold-hoops",
    name: "Gold Everyday Hoops",
    category: "Accessories",
    color: "Gold",
    season: "All Season",
    brand: "Mejuri",
    size: "Small",
    notes: "Goes with everything.",
    image: u("photo-1535632066927-ab7c9ab60908"),
    favorite: true,
    createdAt: "2026-08-30T20:00:00.000Z",
  },
];

export const SAMPLE_OUTFITS: Outfit[] = [
  {
    id: "outfit-gallery-lunch",
    name: "Gallery Lunch",
    notes: "Ivory blouse, wide trousers, slingbacks, cream bag.",
    favorite: true,
    createdAt: "2026-08-31T11:00:00.000Z",
    slots: {
      topId: "item-silk-blouse",
      bottomId: "item-ivory-trousers",
      dressId: null,
      shoesId: "item-slingbacks",
      bagId: "item-cream-bag",
      accessoryId: "item-gold-hoops",
      outerwearId: "item-trench",
    },
  },
  {
    id: "outfit-evening",
    name: "Candlelight Dinner",
    notes: "Black slip, blazer, heels, gold hoops.",
    favorite: true,
    createdAt: "2026-08-20T19:30:00.000Z",
    slots: {
      topId: null,
      bottomId: null,
      dressId: "item-black-dress",
      shoesId: "item-slingbacks",
      bagId: "item-cream-bag",
      accessoryId: "item-gold-hoops",
      outerwearId: "item-black-blazer",
    },
  },
  {
    id: "outfit-weekend",
    name: "Sunday Market",
    notes: "Navy tee, vintage jeans, ballet flats.",
    favorite: false,
    createdAt: "2026-08-10T09:00:00.000Z",
    slots: {
      topId: "item-navy-tee",
      bottomId: "item-blue-jeans",
      dressId: null,
      shoesId: "item-ballet-flats",
      bagId: "item-cream-bag",
      accessoryId: "item-gold-hoops",
      outerwearId: null,
    },
  },
];
